### ISSUE TITLE
Error parsing DS_Store file

### ISSUE THREAD

**Issue by joanbono** [gehaxelt/ds_store#3]
Hi, I'm having errors parsing a DS_Store
I'm using your code:

```go
package main

import (
	"fmt"
	"os"
	"flag"
	"github.com/gehaxelt/ds_store"
	"io/ioutil"
)

func main() {

	var fileName string

	flag.StringVar(&fileName, "i", "", "DS_Store input file")
	flag.Parse()

	if fileName == "" {
		panic("FileName (-i): Must be specified")
	} else if _, err := os.Stat(fileName); os.IsNotExist(err) {
		panic("FileName (-i): File does not exist:" + fileName)
	}

	dat, err := ioutil.ReadFile(fileName)

	if err != nil {
		panic(err)
	}

	a, err := ds_store.NewAllocator(dat)

	filenames, err := a.TraverseFromRootNode()
	if err != nil {
		panic(err)
	}

	for _,f := range filenames {
		fmt.Printf("File: %s \n", f)
	}
}
``` 

I've compiled it:

```bash
go build ds.go
``` 

After executing:

```bash
[/tmp]> ./ds -i DS_Store
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x10a3b76]

goroutine 1 [running]:
github.com/gehaxelt/ds_store.(*Allocator).TraverseFromRootNode(0x0, 0x1803, 0x1a03, 0x0, 0x10f0f60, 0xc00004e240)
	/Users/jbono/go/src/github.com/gehaxelt/ds_store/ds_store.go:188 +0x26
main.main()
	/tmp/ds.go:32 +0x13a
```

It's crashing [in this function](https://github.com/gehaxelt/ds_store/blob/master/ds_store.go#L187)

Attached the DS_Store file as DS_Store.zip since GitHub doesn't allows DS_Store to be uploaded.

[DS_Store.zip](https://github.com/gehaxelt/ds_store/files/2780539/DS_Store.zip)

![image](https://user-images.githubusercontent.com/7288621/51499537-f014b900-1dca-11e9-85d5-6e9b734bf701.png)

**Comment by joanbono** [comment]
Okay looks like an error on the DS_Store file:

Under offset `0x1400`:
![image](https://user-images.githubusercontent.com/7288621/51500817-bbefc700-1dcf-11e9-8f4a-23197b04f5f8.png)

The Table of Contents name's length `0x04` is missing.

**Comment by gehaxelt** [comment]
Hi @joanbono 

thanks for your analysis. I had the same issue of some `.DS_Store` files not being parsable. 

If you compare your screenshots you can see that the top one has one `0x00` byte to few. 

I'm not sure if that's something I can/could/should fix or not? Unfortunately there is no official documentation on the file format, so we can only guess what's wrong here.

**Comment by joanbono** [comment]
Yeah, you are right.
Here the only thing which can be done maybe is to avoid the panic and print something like `Error parsing the DS_Store file`  and not that detailed and long message. But I think it is still "useless" somehow, so I'll close this 😄 

Thanks a lot for your answer and for your library!
